### ISSUE TITLE
feat: Cairo cheatsheet

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#102]
Could be a section in chapter 0 with lots of small, concise examples (Similar to Solidity By Example) showing the multiple uses possible of various useful Cairo syntax.

Non-exhaustive list:
- match
- loop
- felt
- type casting
- arrays
- dict

**Comment by Nonnyjoe** [comment]
Hi, I'll like to handle this

**Comment by julio4** [comment]
Thank you very much. Please keep it concise!

**Comment by Nonnyjoe** [comment]
Sure I'll do that

**Comment by julio4** [comment]
#104 introduced cairo cheatsheet
We keep this issue open for any further additions

**Comment by julio4** [comment]
After some discussion in #126, we will make the examples of this part not contract but only cairo program.
Either hide the contract part with mdbook anchors, or just plain cairo programs.

**Comment by jrmncos** [comment]
hey, is there any improvement to do here? I would like to take it
