### ISSUE TITLE
#[external(v0)] soon deprecated

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#125]
We should replace it by `#[abi(embed_v0)]`

**Comment by julio4** [comment]
#91 for reference.
Actually I'm not sure that `#[external(v0)]` will be deprecated at function level but only at block implementation level.
We should be able to still use `#[external(v0)]` in `#[abi(per_items)]`  from my understanding.

**Comment by enitrat** [comment]
yes indeed
