### ISSUE TITLE
feat: Solidity-compatible keccak hashes

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#14]
In this example, we will show the example of a contract that uses keccak to hash the same values as Solidity.
Waiting for https://github.com/starkware-libs/cairo/issues/3477

**Comment by enitrat** [comment]
blocked: not included in 2.0.x release

**Comment by julio4** [comment]
Update: included in 2.1.0 release.

See [Keccak Support](https://community.starknet.io/t/cairo-v2-1-0-is-out/98136#keccak), with explanation on how to be solidity-compatible by using `keccak_u256s_be_inputs` and `u128_byte_reverse`.
