### ISSUE TITLE
in chapter List, the List  should  never be part of a struct 

### ISSUE THREAD

**Issue by JameWade** [NethermindEth/StarknetByExample#149]
List should never be part of a struct - rather, it should only be used when interacting from / to storage. Otherwise, the internal storage addresses of elements in the struct will collide!!
please look this issue
https://github.com/keep-starknet-strange/alexandria/issues/226

**Comment by julio4** [comment]
Storage structs of smart contracts are a bit different, see there: https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/contract-storage/#storage_variables

You can refer to the `Store` implementation of `List` here:
https://github.com/keep-starknet-strange/alexandria/pull/127

**Comment by julio4** [comment]
Storage structs of smart contracts are a bit different, see there: https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/contract-storage/#storage_variables

You can refer to the Store implementation of List here:
https://github.com/keep-starknet-strange/alexandria/pull/127
