### ISSUE TITLE
feat: Verifying signatures

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#15]
In this example, we will demonstrate how we can use `check_ecdsa_signature` to verify if (`signature_r`, `signature_s`) is a valid ECDSA signature for the given `public_key`

Solidity reference: https://solidity-by-example.org/signature/

**Comment by HansBhatia** [comment]
Taking this on!

**Comment by julio4** [comment]
@HansBhatia Are you still working on it?

Be aware that in [version 2.1.0](https://community.starknet.io/t/cairo-v2-1-0-is-out/98136#secp) there's a way to verify Ethereum signature. See [secp256_trait.cairo](https://github.com/starkware-libs/cairo/blob/2fe68de6ff4d870fb4be064e8e6c263cbef75a51/corelib/src/starknet/secp256_trait.cairo)

**Comment by HansBhatia** [comment]
@julio4 I am not.

**Comment by Akashneelesh** [comment]
I would like to take this up, In this we can generate the signed message through a script, and then perform the functions such as verify signature and recover public key right ?

**Comment by RajeshRk18** [comment]
Can I take up this?

**Comment by Akashneelesh** [comment]
This has already been implemented.

**Comment by julio4** [comment]
> This has already been implemented.

Yes true, closing this now @RajeshRk18. I mistook this issue for another.
