### ISSUE TITLE
feat: Mdbook, use `rustdoc_include` and anchors

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#152]
Related to #70

We can replace `include` with `rustdoc_include` in the mdbook files. 
This allows readers to expand the contract and view the tests directly in the book (without altering the current appearance).

Todo:
- Move all tests into the same contract files
- Adjust listing inclusions in book files
- Insert contract/test anchors as necessary
- Revise the Contribution guidelines to reflect these changes

An example will be provided soon...

**Comment by princeibs** [comment]
Can I hop on this? @julio4
