### ISSUE TITLE
Feature: NFT Dutch Auction

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#187]
### Description

In this example, we will show the implementation of an NFT minting contract using a Dutch Auction, where the minting price follows a decreasing price curve.

### Minting Details

- The seller of the NFT deploys this contract with a `startingPrice`.
- The auction lasts for a specified `duration`.
- The price decreases over time.
- Participants can purchase NFTs at any time as long as the `totalSupply` has not been reached.
- The auction ends when either the `totalSupply` is reached or the `duration` has elapsed.

### Criteria:

- Price is denominated in `IERC20 priceToken`
- Include comprehensive tests
- Deploy the contract on a testnet

### Resources:

- [Solidity By Example - Dutch Auction](https://solidity-by-example.org/app/dutch-auction/)

### ODHack

To be eligible for additional rewards, be sure to review and follow the [ODHack Common Guidelines](https://www.notion.so/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f?pvs=21) and [Contributing Guidelines](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md#contributing).
Be sure to join the telegram group and introduce yourself.

**Comment by princeibs** [comment]
c

**Comment by muheebyusufbaba1** [comment]
I'll like to work on this

**Comment by KodeSage** [comment]
Hello @julio4 , I'm James Harrison, an experienced engineer and have built on the web2 and web3 space. I can work on this task effectively.

**Comment by princeibs** [comment]
Kindly drop link to the StarknetByExample telegram group please.
@julio4

**Comment by saimeunt** [comment]
Hi @julio4, I'm a returning contributor from previous ODHacks ([check my OD profile here](https://app.onlydust.com/u/saimeunt)) and I'd love to handle this issue.

In particular, I have experience porting Solidity code to Cairo as I did in Solidity EIPs to Cairo conversions such as [ERC7496](https://github.com/carbonable-labs/cairo-erc-7496) and [ERC7498](https://github.com/carbonable-labs/cairo-erc-7498).
I will study the Solidity by Example code and carefully replicate it using Cairo and OpenZeppelin ERC20/ERC721 implementations.
I will replace the Solidity price logic using `msg.value` with proper Starknet logic using an ERC20 as price token and `transfer_from` method.
I will include `starknet-foundry` to write comprehensive tests making sure we have 100% coverage for this example and deploy on Starknet Sepolia.

**Comment by saimeunt** [comment]
@princeibs Are you still working on this?
@julio4 Following up on my TimeLock implementation in #201 I'd like to continue working on StarknetByExample and handle this issue (please refer to my previous comment).

**Comment by princeibs** [comment]
Yeah sure. Almost done.
Will be creating a PR asap.

**Comment by julio4** [comment]
> Yeah sure. Almost done. Will be creating a PR asap.

Thank you, please open a draft PR as soon as possible!
