### ISSUE TITLE
Feature: Account Abstraction - Smart Wallet Account Contract

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#188]
### Description

Account Abstraction replace Externally Owned Accounts (EOA). Accounts are implemented as smart contract called smart wallet. 

Each Smart wallet contract must implement the SNIP-6 interface.

In this example, we want to go through each of the SNIP-6 methods and show a simple implementation.

### Criteria:

- Clearly explain what can be customized, comparatively from an EOA.
- Focus on the implementation. There’s already lots of explanations about it in the Starknet Book, give a succinct overview of the most important points.

### Resources:

- [SNIP-6](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-6.md)
- [Starknet Book - Account Abstraction](https://book.starknet.io/ch04-00-account-abstraction.html)

### ODHack

To be eligible for additional rewards, be sure to review and follow the [ODHack Common Guidelines](https://www.notion.so/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f?pvs=21) and [Contributing Guidelines](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md#contributing).
Be sure to join the telegram group and introduce yourself.

**Comment by vibenedict** [comment]
A

**Comment by Jemiiah** [comment]
I would love to work on this project @julio4 🚀

**Comment by VictoriaAde** [comment]
I am interested in working on this.
I have a good idea how I can go about this.
Please assign me.

**Comment by julio4** [comment]
Hello everyone! I assigned @Jemiiah for this time!
