### ISSUE TITLE
Feature: Time locked transactions

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#190]
### Description

In this example, we will show how to implement a contract that takes transactions. After a minimum `waitPeriod`, the locked transaction(s) can be executed.

### Criteria:

- Include comprehensive tests
- Deploy the contract on a testnet

### Ressources:

- [Solidity By Example - Time Lock](https://solidity-by-example.org/app/time-lock/)

### ODHack

To be eligible for additional rewards, be sure to review and follow the [ODHack Common Guidelines](https://www.notion.so/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f?pvs=21) and [Contributing Guidelines](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md#contributing).
Be sure to join the telegram group and introduce yourself.

**Comment by OkoliEvans** [comment]
I can pick this up too Ser @julio4

**Comment by saimeunt** [comment]
Hi @julio4 I'd like to work on this one please.

I will provide an implementation of `TimeLock` as a Cairo Starknet contract using OpenZeppelin `Ownable` (to mirror `onlyOwner` modifier) and a dummy ERC20 to represent the contract ability to trigger eg. a `transferFrom` after a certain `timestamp` has passed.
I will write tests to make sure the example is functional and match exactly the Solidity code behavior.

If necessary, I will refactor `TimeLock` as a Cairo component to showcase how this piece of code could be added as a building block for a user land more complex DAO contract.

**Comment by julio4** [comment]
@saimeunt I assigned you! Thank you very much!
