### ISSUE TITLE
Request to Add Enums in StarknetByExample

### ISSUE THREAD

**Issue by hardiktheprogrammer** [NethermindEth/StarknetByExample#209]
# Description:

This feature request is for adding examples of declaring and importing enums in the starknetbyExample. Enums are a powerful tool in programming, and their usage in StarkNet contracts can enhance code readability and maintainability. Providing clear examples of enum declarations and imports will help developers understand and utilize this feature effectively.

### Criteria:

1. **Enum Declaration:** Show how to declare enums outside of a contract for reusability and modularity.
2. **Enum Imports**: Demonstrate how to import enums into contracts where they are needed.
3. **Example Use Cases**: Provide practical examples of how enums can be used in cairo contracts.
4. **Comprehensive Explanation:** Include detailed explanations and comments to ensure clarity.

**Comment by NueloSE** [comment]
@hardiktheprogrammer can I be assigned to work on this

**Comment by hardiktheprogrammer** [comment]
> @hardiktheprogrammer can I be assigned to work on this

I m not maintainer of this repo
