### ISSUE TITLE
Improvement: Constant Product AMM

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#218]
Adds more explanations for the [Constant Product AMM](https://starknet-by-example.voyager.online/applications/constant-product-amm.html) example.

Details to be Explained:
- approve() the router to spend tokens from the user
- How the swap function works: based on the constant product formula (x * y = k). 
- Number of shares / token ratios for add/rm liquidity. Definition of pool

**Comment by raizo07** [comment]
@julio4 I'll like to be assigned to work on this

**Comment by OkoliEvans** [comment]
> Adds more explanations for the [Constant Product AMM](https://starknet-by-example.voyager.online/ch01/constant-product-amm.html#constant-product-amm) example.

Link is broken

**Comment by OkoliEvans** [comment]
I can take this too if it's okay
