### ISSUE TITLE
Feature: SimpleStorage (Cairo contract + Starknet-js integration)

### ISSUE THREAD

**Issue by egeaybars123** [NethermindEth/StarknetByExample#221]
I prepared a tutorial content for Starknet By Example. The content is about Simple Storage contract in Cairo where the devs are instructed to declare & deploy the contract and interact with its functions using Starknet-js. I believe that adding Cairo contracts with Starknet-js integrations is useful for developers where they can learn to interact with their contracts in one tutorial content.

**Comment by EjembiEmmanuel** [comment]
@egeaybars123 I'd love to work on this if it is open for contribution.

**Comment by Gift-Naomi** [comment]
@egeaybars123 can I be assigned this issue I’m a web3 developer, here is a link to my onlydust profile https://app.onlydust.com/

**Comment by egeaybars123** [comment]
Hey @Gift-Naomi, I'm already working on this in the PR #222 :(
