### ISSUE TITLE
Replace LegacyMap with Map 

### ISSUE THREAD

**Issue by chachaleo** [NethermindEth/StarknetByExample#242]
* Map sub-chapter still uses the depreciated `LegacyMap` type, updating the Mapping chapter with the type `Map`
* Modify in other section using `LegacyMap`

I'll be happy to take care of this

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue

**Comment by ScottyDavies** [comment]
Hi @chachaleo Please can you assign this task to me so I can start working on it immediately.

**Comment by julio4** [comment]
This will be handled at once in #245
