### ISSUE TITLE
feat: Custom StorageAccess implementation (packing)

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#25]
In this example, we will implement a custom StorageAccess implementation for a struct. 
We will demonstrate how we can pack multiple fields together instead of storing them in different storage addresses.

You will optimize storage by packing values together using bitshifts and bitmasks inside the `read_at_offset_internal` and `write_at_offset_internal` methods of the `StorageAccess` trait.

For example,
```rust
struct Vote{
   proposal_id: u8,
   timestamp: u32, 
   value: bool,
}
```

**Comment by julio4** [comment]
Updated in #62
