### ISSUE TITLE
Fix search - search either does not search text or specifically doesn't search inside code blocks. 

### ISSUE THREAD

**Issue by JorikSchellekens** [NethermindEth/StarknetByExample#274]
![image](https://github.com/user-attachments/assets/30f15ee6-90b7-4e63-a6a5-4898db0c3d68)

**Comment by Nanle100** [comment]
i can solve this issue

**Comment by JorikSchellekens** [comment]
Hey, any progress?

**Comment by Nanle100** [comment]
where can i find the search component?

**Comment by julio4** [comment]
Fixed in deployment pipeline
