### ISSUE TITLE
`unwrap_syscall` replaced by `unwrap`

### ISSUE THREAD

**Issue by JorikSchellekens** [NethermindEth/StarknetByExample#275]
At least as of Cairo 2.9.1 `unwrap_syscall` has been replaced by `unwrap`. There are quite a few references to `unwrap_syscall` across the codebase.

**Comment by fishonamos** [comment]
Let me work on this @JorikSchellekens

**Comment by julio4** [comment]
We'll add this in cairo 2.9+ release!
