### ISSUE TITLE
Update some text descriptions

### ISSUE THREAD

**Issue by CountryCousin** [NethermindEth/StarknetByExample#276]
Since the ability to view hidden codes was removed, I guess it kind of makes sense to update this part of the Book

<img width="801" alt="Screenshot 2024-12-09 at 17 17 04" src="https://github.com/user-attachments/assets/d7daca48-77bf-42c3-8d72-1b1f611c1b95">

**Comment by Birdmannn** [comment]
Hi, can I handle this task? I'm Pascal, and cairo-starknet developer with a few contributions on open source projects, and a graduate of Basecamp. I can find this in the book and update it's contents. ETA < 20 minutes
