### ISSUE TITLE
feat: defining and storing user-defined types

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#3]
In this contract, we will create a user-defined `struct` and store that struct in storage. 
We will introduce the `StorageAccess` trait, and implement this trait for our custom struct.

We will also demonstrate in a second example how we can use the `#[derive(StorageAccess]` attribute to automatically generate the code required to store that struct in storage.

**Comment by swapnilraj** [comment]
We should also include storing Arrays in storage

**Comment by enitrat** [comment]
> We should also include storing Arrays in storage

There's currently no implementation of this. Should we create our own (naively, store length at address 0, and then store elements from address 1 to n+1) ?

**Comment by swapnilraj** [comment]
> > We should also include ss in storage
> 
> There's currently no implementation of this. Should we create our own (naively, store length at address 0, and then store elements from address 1 to n+1) ?

Yea. that sounds reasonable, Warp's storage model did that as well.

**Comment by enitrat** [comment]
Well, someone frontran us https://twitter.com/0xChqrles/status/1665104126802370561 👀 
cc @0xchqrles can we show your implementation for CairoByExample? 😄 

Something that is worth considering is that 
> If it is a mapping to complex values (e.g., tuples or structs), then this complex value lies in a continuous segment starting from the address calculated in the previous point. Note that 256 field elements is the current limitation on the maximal size of a complex storage value.

That's why Charles implementation is limited to 255 elements. 
In order to store more than 255 elements, we might need to implement an even more hacky behavior, where the 255th element is the address of the beginning of the next segment, whose address is calculated as `sn_keccak(variable_name + i)` where i is the array chunk. wdyt?

**Comment by enitrat** [comment]
Same remark as in #4 
I think our example should only show that we can store common non-array custom types with `#derive[(StorageAccess)]`.

I will create another issue to store arrays

**Comment by 0xChqrles** [comment]
Thanks for asking @enitrat You can obviously use my code for whatever you want

And since keccak is expensive why not using something like: `pedersen(storage_address, segment_id)` as the address of the new segment, I think it is already what legacyMap do but with 256 times more pedersen ^^

**Comment by enitrat** [comment]
> why not using something like: pedersen(storage_address, segment_id)

Even better, I'm actually working on something similar and using Poseidon to calculate storage addresses, as it's a zk-friendly hash function and the cheapest one I believe!
