### ISSUE TITLE
[feat] Wasm cairo integration for Playground. 

### ISSUE THREAD

**Issue by cryptonerdcn** [NethermindEth/StarknetByExample#35]
Because [CairoByExample](https://github.com/NethermindEth/CairoByExample) is made by mdbook, we could also use the Wasm-Cairo as a playground.

Like this PR in Cairo-book Repo
https://github.com/cairo-book/cairo-book.github.io/pull/244

**Comment by cryptonerdcn** [comment]
@enitrat I need a `theme/index.hbs` to make it works. Are we considering adding a template? Just a default plain one is very enough.

**Comment by enitrat** [comment]
Hey @cryptonerdcn, CairoByExample mostly focuses on contract syntax so I'm not sure whether it's relevant here, given that we can't really execute contracts, unlike programs. Let me think about this - I appreciate the initiative though!

**Comment by julio4** [comment]
Including a link to remix with the upcoming Cairo1 remix plugin would be more relevant I think. However, great work on `cairo-wasm`! It's a great feature for the Cairo book.

**Comment by enitrat** [comment]
@cryptonerdcn For now let's keep it as an open issue so that it doesn't make the build too heavy, we'll integrate it if we have pure Cairo programs in the future.
