### ISSUE TITLE
feat: struct as mapping key

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#48]
While we cannot directly use structs as `LegacyMap` keys, what we can do is hash the fields of the struct together and use the has as key.

In this example, we will define a custom struct with multiple fields. We will implement a `hash` method on that structs, that returns the poseidon hash of all the fields. We will then use this hash as the key for our custom mapping.

```rust
map::write(my_struct.hash(), value)
```

**Comment by StarkFishinator** [comment]
I'll take this one !

**Comment by enitrat** [comment]
@StarkFishinator awesome, let me know if you need any guidance

**Comment by enitrat** [comment]
Closed by #49
