### ISSUE TITLE
Can I make a traits page?

### ISSUE THREAD

**Issue by neelkamath** [NethermindEth/StarknetByExample#50]
@enitrat We mention traits but there's no docs on it even though we have other basics like if statements.

**Comment by enitrat** [comment]
I don't think it has any value added given that it's already covered in the book https://cairo-book.github.io/ch07-02-traits-in-cairo.html and I 

If statements are indeed out of context here, I might remove them in the future. Let's focus on providing examples directly related to contracts and some use cases
