### ISSUE TITLE
feat: implicit/explicit contract interfaces

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#54]
With the new contract syntax, there are two "ways" of writing contracts.

1. Explicitly define the contract interface and writing the implementation that matches this interface.
2. Use the `#[generate_trait]` attribute to derive the contract interface from its implementation.

**Comment by julio4** [comment]
You can assign me!

**Comment by enitrat** [comment]
💪  as this is still brand new, don't hesitate to ask for help! The `generate_trait` mechanism is not properly documented yet.

**Comment by enitrat** [comment]
@julio4 I wrote about it in the cairo book recently. https://book.cairo-lang.org/ch99-01-03-04-reducing-boilerplate.html
