### ISSUE TITLE
feat: Remix cairo integration

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#60]
Now that the `Remix Starknet plugin` has been released, we can consider linking each example to a remix workspace with the corresponding contracts. This will enable readers to experiment directly with the contract in their browser.

**Comment by enitrat** [comment]
Great idea. I think the easiest way is to provide links to the raw content, so that users can import them with HTTP.
https://remix-ide.readthedocs.io/en/latest/import.html

**Comment by julio4** [comment]
We can use some remix args!

Activate the Starknet plugin automatically: 
`#activate=Starknet-cairo1-compiler`

Load a specific file by url:
`url=https://github.com/NethermindEth/StarknetByExample/blob/main/listings/ch00-introduction/constructor/src/lib.cairo`

Example of loading a single file and automatically load the Starknet remix plugin:
`https://remix.ethereum.org/?#activate=Starknet-cairo1-compiler&url=https://github.com/NethermindEth/StarknetByExample/blob/main/listings/ch00-introduction/constructor/src/lib.cairo`

As the Starknet remix plugin only support single stand-alone files, this is sufficient for now.
Also, the Remix Starknet Plugin don't support the v2 syntax for now, so let's wait for that first.

**Comment by enitrat** [comment]
Amazing!
