### ISSUE TITLE
Tests runs are not repeatable

### ISSUE THREAD

**Issue by eliotstock** [NethermindEth/StarknetByExample#64]
Actual: `test_set_as_owner - panicked with [144402577857143122995078514 ('wrong owner'), ].`

Expected: passes

**Comment by eliotstock** [comment]
Or could it be that this test passes only on the first test run, and `test_set_as_owner()` is the opposite: it fails on the first run then passes for subsequent runs?

**Comment by julio4** [comment]
Thanks for spotting the issue. We need to use `set_contract_address` not `set_caller_address` to fake the owner. Fixed in #65
