### ISSUE TITLE
feat: Hash trait 

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#69]
Show an example that use `#[derive(Hash)]` to hash an user defined type.
Show how to use different hashing functions: Poseidon and Pedersen.

See [here](https://community.starknet.io/t/cairo-v2-2-0-is-out/99263#hash) for documentation

**Comment by julio4** [comment]
We are now using the Hash trait in the "Struct as mapping key" example. We can reference it in the specific Hash trait example.

**Comment by OkoliEvans** [comment]
@julio4 If no one has taken this up I will like to take it

**Comment by enitrat** [comment]
fyi https://book.cairo-lang.org/ch11-03-hash.html

**Comment by julio4** [comment]
@OkoliEvans Any progress so far?

**Comment by OkoliEvans** [comment]
> @OkoliEvans Any progress so far?
Yeah, I will open a PR soon. I am still trying to figure out how to write a test for the hash functions. @julio4

**Comment by julio4** [comment]
> @OkoliEvans Any progress so far?
> Yeah, I will open a PR soon. I am still trying to figure out how to write a test for the hash functions. @julio4

> @fontanellag Same here. I also was able to compute Pedersen and Poseidon hashes of a custom struct but how we can test their validity? We should compare the results with the hashes provided from another tool?

It is enough to compare the result against an hardcoded constant value. You can compute the expected result using cairo or [other implementations](https://docs.starknet.io/documentation/architecture_and_concepts/Cryptography/hash-functions/)

**Comment by fontanellag** [comment]
Created a draft PR https://github.com/NethermindEth/StarknetByExample/pull/159
