### ISSUE TITLE
feat: Commit-Reveal scheme

### ISSUE THREAD

**Issue by julio4** [NethermindEth/StarknetByExample#77]

**Comment by OkoliEvans** [comment]
Is it possible to have a description for this issue? @julio4

**Comment by julio4** [comment]
> Is it possible to have a description for this issue? @julio4

I'll point you to this [video](https://www.youtube.com/watch?v=7AbdpTWQ9nU) from Austin Griffith.
This simple scheme use the hash of a value as a commitment, where the value can be revealed later while checking that the commitment was valid.

**Comment by OkoliEvans** [comment]
> > Is it possible to have a description for this issue? @julio4
> 
> I'll point you to this [video](https://www.youtube.com/watch?v=7AbdpTWQ9nU) from Austin Griffith. This simple scheme use the hash of a value as a commitment, where the value can be revealed later while checking that the commitment was valid.

Okay, I'll go through this and get back to you ASAP

**Comment by LamsyA** [comment]
I would like to work on this issue.

**Comment by julio4** [comment]
> I would like to work on this issue.

@OkoliEvans Did you worked a bit on this? If not, @LamsyA can start working on it!

**Comment by OkoliEvans** [comment]
I have not started working on it, he can take it. @julio4

**Comment by LamsyA** [comment]
I have implemented the commitment scheme and  created a PR  #184 

@julio4  kindly check it out.

**Comment by RJMadrigal** [comment]
@igaray i would like to take this :)

**Comment by LamsyA** [comment]
@julio4 kindly review  #184 

> I have implemented the commitment scheme and created a PR #184
> 
> @julio4 kindly check it out.

**Comment by julio4** [comment]
> @julio4 kindly review #184

I already reviewed it and asked for a few change, please check it again!

**Comment by Villegas2003** [comment]
Hi @glihm ,

I'm a software developer and a student at Universidad Cenfotec, as well as a strong interest in blockchain technology.

I'd like to contribute to the project by working on this issue. Could you please assign it to me if it's still available?

**Comment by glihm** [comment]
@Villegas2003 I'm not maintainer here, and as you can see in the comment's history and issue details, it is already assigned. 👍

**Comment by Villegas2003** [comment]
@glihm Thank you for your prompt response 👍

**Comment by LamsyA** [comment]
@julio4  Kindly review the code, I have done what you requested in the comment.

thanks
