### ISSUE TITLE
"Counter" contract example not fetching (?)

### ISSUE THREAD

**Issue by MathiasTELITSINE** [NethermindEth/StarknetByExample#80]
![Fetching error](https://github.com/NethermindEth/StarknetByExample/assets/95372106/b8ee8ce9-3cca-4212-959c-f571527c6429)
Looks like the "counter" contract example (https://starknet-by-example.voyager.online/ch00-11-counter.html) isn't working properly on Remix. There is a "Failed to fetch" error when trying to compile it.

**Comment by julio4** [comment]
Hey! I just checked and I didn't have the error. It might have been a internet connectivity issue.
