### ISSUE TITLE
feat: L1 -> L2 messaging

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/StarknetByExample#9]
This example will show how we can send a message to L2 from L1 and execute a function from a L2 contract annotated with `#[l1_handler]`. We will provide both Solidity code and Cairo code.

**Comment by julio4** [comment]
I will try this one!

**Comment by julio4** [comment]
You can use [this messaging workshop ](https://github.com/starknet-edu/starknet-messaging-bridge) to get started.

**Comment by enitrat** [comment]
also the book now has a section on it, so I think we should just provide a very succinct view into how it's implemented with a simple example

**Comment by julio4** [comment]
I agree! See [Starknet Book - L1-L2 messaging](https://docs.starknet.io/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/)
